/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "departures_board.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(StopBasic, StopBasic, AUTO)


PB_BIND(StopEventBasic, StopEventBasic, 2)


PB_BIND(AlertBasic, AlertBasic, 2)


PB_BIND(DeparturesBoardResponse, DeparturesBoardResponse, 4)


PB_BIND(DeparturesBoardRequest, DeparturesBoardRequest, AUTO)





