/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_DEPARTURES_BOARD_PB_H_INCLUDED
#define PB_DEPARTURES_BOARD_PB_H_INCLUDED
#include "../nanopb/pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _RouteType {
    RouteType_TRAM = 0,
    RouteType_METRO = 1,
    RouteType_RAIL = 2,
    RouteType_BUS = 3,
    RouteType_FERRY = 4,
    RouteType_CABLE_CAR = 5,
    RouteType_AERIAL = 6,
    RouteType_FUNICULAR = 7,
    RouteType_TROLLEYBUS = 11,
    RouteType_MONORAIL = 12
} RouteType;

/* Struct definitions */
typedef struct _StopBasic {
    /* required */
    bool has_stop_name;
    char stop_name[64];
    /* required */
    bool has_timezone;
    char timezone[40];
    /* required */
    bool has_timezone_offset;
    int32_t timezone_offset;
} StopBasic;

/* https://birchdeparturesfromstop.catenarymaps.org/departures_at_stop?stop_id=CUS&chateau_id=metra&greater_than_time=1782583302&less_than_time=1782586913&include_shapes=false
 Mostly from event, but some data must be looked up */
typedef struct _StopEventBasic { /* From events (catenary-backend/src/birch/departures_at_osm_station.rs StopEvent) */
    /* optional */
    bool has_scheduled_arrival;
    int32_t scheduled_arrival;
    /* optional */
    bool has_scheduled_departure;
    int32_t scheduled_departure;
    /* optional */
    bool has_realtime_arrival;
    int32_t realtime_arrival;
    /* optional */
    bool has_realtime_departure;
    int32_t realtime_departure;
    /* required */
    bool has_trip_modified;
    bool trip_modified;
    /* required */
    bool has_stop_cancelled;
    bool stop_cancelled;
    /* required */
    bool has_trip_cancelled;
    bool trip_cancelled;
    /* required */
    bool has_trip_deleted;
    bool trip_deleted;
    /* required */
    bool has_trip_id;
    char trip_id[64];
    /* optional */
    bool has_headsign;
    char headsign[64];
    /* optional */
    bool has_vehicle_number;
    char vehicle_number[16];
    /* optional */
    bool has_trip_short_name;
    char trip_short_name[16];
    /* required */
    bool has_route_name;
    char route_name[32];
    /* optional */
    bool has_route_color;
    uint32_t route_color; /* GColor8 argb byte; default white */
    /* optional */
    bool has_route_text_color;
    uint32_t route_text_color; /* GColor8 argb byte; default black */
    /* required */
    bool has_route_type;
    RouteType route_type;
    /* required */
    bool has_agency_name;
    char agency_name[64];
} StopEventBasic;

/* catenary-backend/src/aspen_dataset.rs AspenisedAlert
 https://gtfs.org/documentation/realtime/reference/#message-alert */
typedef struct _AlertBasic {
    /* required */
    bool has_header_text;
    char header_text[128];
    /* required */
    bool has_description_text;
    char description_text[512];
} AlertBasic;

typedef struct _DeparturesBoardResponse {
    /* required */
    bool has_success;
    bool success;
    /* The following fields may be ommitted if not successful. */
    bool has_stop;
    StopBasic stop;
    pb_size_t alerts_count;
    AlertBasic alerts[16];
    pb_size_t stop_events_count;
    StopEventBasic stop_events[16];
    bool has_truncated;
    bool truncated;
} DeparturesBoardResponse;

typedef struct _DeparturesBoardRequest {
    /* required */
    bool has_chateau_id;
    char chateau_id[64];
    /* required */
    bool has_stop_id;
    char stop_id[64];
    /* required */
    bool has_greater_than_time;
    int32_t greater_than_time;
    /* required */
    bool has_less_than_time;
    int32_t less_than_time;
} DeparturesBoardRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _RouteType_MIN RouteType_TRAM
#define _RouteType_MAX RouteType_MONORAIL
#define _RouteType_ARRAYSIZE ((RouteType)(RouteType_MONORAIL+1))


#define StopEventBasic_route_type_ENUMTYPE RouteType





/* Initializer values for message structs */
#define StopBasic_init_default                   {false, "", false, "", false, 0}
#define StopEventBasic_init_default              {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, "", false, "", false, "", false, "", false, "", false, 255u, false, 0u, false, _RouteType_MIN, false, ""}
#define AlertBasic_init_default                  {false, "", false, ""}
#define DeparturesBoardResponse_init_default     {false, false, false, StopBasic_init_default, 0, {AlertBasic_init_default, AlertBasic_init_default, AlertBasic_init_default, AlertBasic_init_default, AlertBasic_init_default, AlertBasic_init_default, AlertBasic_init_default, AlertBasic_init_default, AlertBasic_init_default, AlertBasic_init_default, AlertBasic_init_default, AlertBasic_init_default, AlertBasic_init_default, AlertBasic_init_default, AlertBasic_init_default, AlertBasic_init_default}, 0, {StopEventBasic_init_default, StopEventBasic_init_default, StopEventBasic_init_default, StopEventBasic_init_default, StopEventBasic_init_default, StopEventBasic_init_default, StopEventBasic_init_default, StopEventBasic_init_default, StopEventBasic_init_default, StopEventBasic_init_default, StopEventBasic_init_default, StopEventBasic_init_default, StopEventBasic_init_default, StopEventBasic_init_default, StopEventBasic_init_default, StopEventBasic_init_default}, false, false}
#define DeparturesBoardRequest_init_default      {false, "", false, "", false, 0, false, 0}
#define StopBasic_init_zero                      {false, "", false, "", false, 0}
#define StopEventBasic_init_zero                 {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, "", false, "", false, "", false, "", false, "", false, 0, false, 0, false, _RouteType_MIN, false, ""}
#define AlertBasic_init_zero                     {false, "", false, ""}
#define DeparturesBoardResponse_init_zero        {false, 0, false, StopBasic_init_zero, 0, {AlertBasic_init_zero, AlertBasic_init_zero, AlertBasic_init_zero, AlertBasic_init_zero, AlertBasic_init_zero, AlertBasic_init_zero, AlertBasic_init_zero, AlertBasic_init_zero, AlertBasic_init_zero, AlertBasic_init_zero, AlertBasic_init_zero, AlertBasic_init_zero, AlertBasic_init_zero, AlertBasic_init_zero, AlertBasic_init_zero, AlertBasic_init_zero}, 0, {StopEventBasic_init_zero, StopEventBasic_init_zero, StopEventBasic_init_zero, StopEventBasic_init_zero, StopEventBasic_init_zero, StopEventBasic_init_zero, StopEventBasic_init_zero, StopEventBasic_init_zero, StopEventBasic_init_zero, StopEventBasic_init_zero, StopEventBasic_init_zero, StopEventBasic_init_zero, StopEventBasic_init_zero, StopEventBasic_init_zero, StopEventBasic_init_zero, StopEventBasic_init_zero}, false, 0}
#define DeparturesBoardRequest_init_zero         {false, "", false, "", false, 0, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define StopBasic_stop_name_tag                  1
#define StopBasic_timezone_tag                   2
#define StopBasic_timezone_offset_tag            3
#define StopEventBasic_scheduled_arrival_tag     1
#define StopEventBasic_scheduled_departure_tag   2
#define StopEventBasic_realtime_arrival_tag      3
#define StopEventBasic_realtime_departure_tag    4
#define StopEventBasic_trip_modified_tag         5
#define StopEventBasic_stop_cancelled_tag        6
#define StopEventBasic_trip_cancelled_tag        7
#define StopEventBasic_trip_deleted_tag          8
#define StopEventBasic_trip_id_tag               9
#define StopEventBasic_headsign_tag              10
#define StopEventBasic_vehicle_number_tag        11
#define StopEventBasic_trip_short_name_tag       12
#define StopEventBasic_route_name_tag            13
#define StopEventBasic_route_color_tag           14
#define StopEventBasic_route_text_color_tag      15
#define StopEventBasic_route_type_tag            16
#define StopEventBasic_agency_name_tag           17
#define AlertBasic_header_text_tag               1
#define AlertBasic_description_text_tag          2
#define DeparturesBoardResponse_success_tag      1
#define DeparturesBoardResponse_stop_tag         2
#define DeparturesBoardResponse_alerts_tag       3
#define DeparturesBoardResponse_stop_events_tag  4
#define DeparturesBoardResponse_truncated_tag    5
#define DeparturesBoardRequest_chateau_id_tag    1
#define DeparturesBoardRequest_stop_id_tag       2
#define DeparturesBoardRequest_greater_than_time_tag 3
#define DeparturesBoardRequest_less_than_time_tag 4

/* Struct field encoding specification for nanopb */
#define StopBasic_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   stop_name,         1) \
X(a, STATIC,   OPTIONAL, STRING,   timezone,          2) \
X(a, STATIC,   OPTIONAL, SINT32,   timezone_offset,   3)
#define StopBasic_CALLBACK NULL
#define StopBasic_DEFAULT NULL

#define StopEventBasic_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, SFIXED32, scheduled_arrival,   1) \
X(a, STATIC,   OPTIONAL, SFIXED32, scheduled_departure,   2) \
X(a, STATIC,   OPTIONAL, SFIXED32, realtime_arrival,   3) \
X(a, STATIC,   OPTIONAL, SFIXED32, realtime_departure,   4) \
X(a, STATIC,   OPTIONAL, BOOL,     trip_modified,     5) \
X(a, STATIC,   OPTIONAL, BOOL,     stop_cancelled,    6) \
X(a, STATIC,   OPTIONAL, BOOL,     trip_cancelled,    7) \
X(a, STATIC,   OPTIONAL, BOOL,     trip_deleted,      8) \
X(a, STATIC,   OPTIONAL, STRING,   trip_id,           9) \
X(a, STATIC,   OPTIONAL, STRING,   headsign,         10) \
X(a, STATIC,   OPTIONAL, STRING,   vehicle_number,   11) \
X(a, STATIC,   OPTIONAL, STRING,   trip_short_name,  12) \
X(a, STATIC,   OPTIONAL, STRING,   route_name,       13) \
X(a, STATIC,   OPTIONAL, UINT32,   route_color,      14) \
X(a, STATIC,   OPTIONAL, UINT32,   route_text_color,  15) \
X(a, STATIC,   OPTIONAL, UENUM,    route_type,       16) \
X(a, STATIC,   OPTIONAL, STRING,   agency_name,      17)
#define StopEventBasic_CALLBACK NULL
#define StopEventBasic_DEFAULT (const pb_byte_t*)"\x70\xff\x01\x78\x00\x00"

#define AlertBasic_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   header_text,       1) \
X(a, STATIC,   OPTIONAL, STRING,   description_text,   2)
#define AlertBasic_CALLBACK NULL
#define AlertBasic_DEFAULT NULL

#define DeparturesBoardResponse_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     success,           1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  stop,              2) \
X(a, STATIC,   REPEATED, MESSAGE,  alerts,            3) \
X(a, STATIC,   REPEATED, MESSAGE,  stop_events,       4) \
X(a, STATIC,   OPTIONAL, BOOL,     truncated,         5)
#define DeparturesBoardResponse_CALLBACK NULL
#define DeparturesBoardResponse_DEFAULT (const pb_byte_t*)"\x08\x00\x28\x00\x00"
#define DeparturesBoardResponse_stop_MSGTYPE StopBasic
#define DeparturesBoardResponse_alerts_MSGTYPE AlertBasic
#define DeparturesBoardResponse_stop_events_MSGTYPE StopEventBasic

#define DeparturesBoardRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, STRING,   chateau_id,        1) \
X(a, STATIC,   OPTIONAL, STRING,   stop_id,           2) \
X(a, STATIC,   OPTIONAL, SFIXED32, greater_than_time,   3) \
X(a, STATIC,   OPTIONAL, SFIXED32, less_than_time,    4)
#define DeparturesBoardRequest_CALLBACK NULL
#define DeparturesBoardRequest_DEFAULT NULL

extern const pb_msgdesc_t StopBasic_msg;
extern const pb_msgdesc_t StopEventBasic_msg;
extern const pb_msgdesc_t AlertBasic_msg;
extern const pb_msgdesc_t DeparturesBoardResponse_msg;
extern const pb_msgdesc_t DeparturesBoardRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define StopBasic_fields &StopBasic_msg
#define StopEventBasic_fields &StopEventBasic_msg
#define AlertBasic_fields &AlertBasic_msg
#define DeparturesBoardResponse_fields &DeparturesBoardResponse_msg
#define DeparturesBoardRequest_fields &DeparturesBoardRequest_msg

/* Maximum encoded size of messages (where known) */
#define AlertBasic_size                          644
#define DEPARTURES_BOARD_PB_H_MAX_SIZE           DeparturesBoardResponse_size
#define DeparturesBoardRequest_size              140
#define DeparturesBoardResponse_size             15414
#define StopBasic_size                           112
#define StopEventBasic_size                      306

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
