try {

// MARK: - Front matter

// Polyfills for TextDecoder and TextEncoder
// required for pbjs-minimal.js
require('fast-text-encoding');

var keys = require('message_keys');

console.log("catenary-proto PKJS process");

var dbproto = require('./proto/departures_board.pb.js');
console.log("Success importing proto");

const ChunkType = {
  DeparturesBoardRequest: 0,
  DeparturesBoardResponse: 1,
  JSReady: 2,
};

// Should be same as comm.h MAX_INBOX_CHUNK_SIZE
const MAX_CHUNK_SIZE = 960;

// try {
// } catch (e) {
//   console.log("Error requiring proto: " + e.message);
//   console.log("Stack: " + e.stack);
// }

const GColorPastelYellowARGB8 = 0b11111110;
const GColorBlackARGB8 = 0b11000000;
const GColorDarkGreenARGB8 = 0b11000100;
const GColorWhiteARGB8 = 0b11111111;

const FIELD_SIZES = {
  // String fields
  // '\0' is the last character
  headsign:        64 - 1,
  vehicle_number:  16 - 1,
  trip_short_name: 16 - 1,
  route_name:      32 - 1,
  agency_name:     64 - 1,
  stop_name:       64 - 1,
  timezone:        40 - 1,
  header_text:     128 - 1,
  description_text: 512 - 1,

  // Array fields
  alerts: 16,
  stop_events: 16,
};

// MARK: - Basic utilities

// xhrRequest is from Pebble tutorial
function xhrRequest(url, type, callback, errorCallback = function(){
  console.log("Error fetching URL " + url);
}) {
	var xhr = new XMLHttpRequest();
	xhr.onload = function() {
    if(this.status >= 200 && this.status < 300) {
      callback(this.responseText);
    } else {
      errorCallback();
    }
	};
  xhr.onerror = errorCallback;
  xhr.onabort = errorCallback;
	xhr.open(type, url);
	xhr.send();
}

// getUtcOffsetSeconds is generated by Claude-Sonnet-4.6
function getUtcOffsetSeconds(ianaTimezone, unixTimestamp, callback) {
  var xhr = new XMLHttpRequest();
  var url = 'https://timeapi.io/api/timezone/zone?timeZone=' + encodeURIComponent(ianaTimezone);
  xhr.open('GET', url);
  xhr.onload = function() {
    var data = JSON.parse(xhr.responseText);
    // currentUtcOffset is in hours; convert to seconds
    callback(data.currentUtcOffset.seconds);
  };
  xhr.onerror = function() {
    console.log('Timezone API request failed');
  };
  xhr.send();
}

// hexToGColor8Argb is generated by Claude-Sonnet-4.6
function hexToGColor8Argb(hexStr, alpha = 255) {
  // console.log("hexToGColor8Argb(" + hexStr + ", " + alpha + ")");
  // Strip leading '#' if present
  let hex = hexStr.replace(/^#/, '');

  // Support shorthand hex (#fff -> #ffffff)
  if (hex.length === 3) {
    hex = hex.split('').map(c => c + c).join('');
  }

  if (!/^[0-9a-fA-F]{6}$/.test(hex)) {
    throw new Error(`Invalid hex color string: "${hexStr}"`);
  }

  const red = parseInt(hex.substring(0, 2), 16);
  const green = parseInt(hex.substring(2, 4), 16);
  const blue = parseInt(hex.substring(4, 6), 16);

  // Mirror the C macro: each 8-bit channel keeps only its top 2 bits (>> 6)
  const r = (red >> 6) & 0x3;
  const g = (green >> 6) & 0x3;
  const b = (blue >> 6) & 0x3;
  const a = (alpha >> 6) & 0x3;

  // GColor8's bitfields (b, g, r, a, declared low-to-high) pack into a byte as:
  // argb = a<<6 | r<<4 | g<<2 | b
  const argb = (a << 6) | (r << 4) | (g << 2) | b;

  return argb; // 0-255, matches the .argb field of the union
}

// Generated by Claude-Sonnet-4.6
/**
 * Truncate a string so its UTF-8 encoding fits within maxUtf8Bytes bytes.
 * Does not split multi-byte sequences or surrogate pairs.
 *
 * Pass (nanopb_max_size - 1) as maxUtf8Bytes to account for the null terminator
 * nanopb appends in the char array.
 */
function truncateToUtf8Bytes(str, maxUtf8Bytes) {
  if(!str) {
    return str;
  }
  var byteCount = 0;
  var i = 0;
  while (i < str.length) {
    var code = str.charCodeAt(i);
    var charBytes;
    var advance;

    if (code >= 0xD800 && code <= 0xDBFF) {
      // High surrogate — consume the pair, encodes to 4 UTF-8 bytes
      charBytes = 4;
      advance = 2;
    } else if (code < 0x80) {
      charBytes = 1;
      advance = 1;
    } else if (code < 0x800) {
      charBytes = 2;
      advance = 1;
    } else {
      // U+0800–U+FFFF (BMP, excludes surrogates already handled above)
      charBytes = 3;
      advance = 1;
    }

    if (byteCount + charBytes > maxUtf8Bytes) break;
    byteCount += charBytes;
    i += advance;
  }
  return str.slice(0, i);
}

function findEnglish(translation) {
  let found = translation.find((translation) => translation.language.toLowerCase().startsWith("en"));
  if(found) { return found.text; }
  if(translation.length > 0) return translation[0].text;
  return "";
}

// MARK: - Processing departures board

function getDeparturesBoard(stop_id, chateau_id, greater_than_time, less_than_time) {
  // var url = "https://birchdeparturesfromstop.catenarymaps.org/departures_at_stop?stop_id=CUS&chateau_id=metra&greater_than_time=1782583302&less_than_time=1782586913&include_shapes=false";
  let url = `https://birchdeparturesfromstop.catenarymaps.org/departures_at_stop?stop_id=${stop_id}&chateau_id=${chateau_id}&greater_than_time=${greater_than_time}&less_than_time=${less_than_time}&include_shapes=false`;

  xhrRequest(url, 'GET', function(response_text){
    try {
    var json = JSON.parse(response_text);

    console.log("Got departures board from Internet");
    // console.log("Departures board from Internet:");
    // console.log(response_text);

    var response_data = {
      success: true,
      stop: {
        // TODO - More intelligent translations handling
        stop_name: truncateToUtf8Bytes(json.primary.stop_name_translations.EN, FIELD_SIZES.stop_name),
        timezone: truncateToUtf8Bytes(json.primary.timezone, FIELD_SIZES.timezone),
        timezone_offset: 0,
      },
      alerts: [],
      stop_events: [],

      // TODO - Allow continuing to stream a truncated response
      truncated: false,
    };

    for(let chateau_alerts of Object.values(json.alerts)) {
      for(let alert_data of Object.values(chateau_alerts)) {
        // console.log("Processing alert");
        // console.log(JSON.stringify(alert_data));
        if(response_data.alerts.length >= FIELD_SIZES.alerts) {
          response_data.truncated = true;
          break;
        }
        response_data.alerts.push({
          header_text: truncateToUtf8Bytes(
            findEnglish(alert_data.header_text.translation),
            FIELD_SIZES.header_text
          ),
          description_text: truncateToUtf8Bytes(
            findEnglish(alert_data.description_text.translation),
            FIELD_SIZES.description_text
          ),
        });
      }
    }

    for(let event_data of json.events) {
      // console.log("Processing stop event");
      // console.log(JSON.stringify(event_data));
      if(response_data.stop_events.length >= FIELD_SIZES.stop_events) {
        response_data.truncated = true;
        break;
      }
      
      const route = json.routes[event_data.chateau][event_data.route_id];
      const agency = json.agencies[route.chateau][route.agency_id];

      response_data.stop_events.push({
        scheduled_arrival: event_data.scheduled_arrival,
        scheduled_departure: event_data.scheduled_departure,

        trip_modified: event_data.trip_modified,
        stop_cancelled: event_data.stop_cancelled,
        trip_cancelled: event_data.trip_cancelled,
        trip_deleted: event_data.trip_deleted,

        headsign: truncateToUtf8Bytes(event_data.headsign, FIELD_SIZES.headsign),
        vehicle_number: truncateToUtf8Bytes(event_data.vehicle_number, FIELD_SIZES.vehicle_number),
        trip_short_name: truncateToUtf8Bytes(event_data.trip_short_name, FIELD_SIZES.trip_short_name),

        // TODO - Handle translations and absence of translations for route stuff
        route_name: truncateToUtf8Bytes(
          route.short_name ? route.short_name : route.long_name, 
          FIELD_SIZES.route_name),
        route_color: route.color ? hexToGColor8Argb(route.color) : GColorWhiteARGB8,
        route_text_color: route.text_color ? hexToGColor8Argb(route.text_color) : GColorBlackARGB8,
        route_type: route.route_type,

        // TODO - Handle translations and absence of translations for agency name
        agency_name: truncateToUtf8Bytes(agency.agency_name, FIELD_SIZES.agency_name),
      });
    }

    getUtcOffsetSeconds(json.primary.timezone, greater_than_time, offset => {
      try {
      console.log("Successfully got timezone offset");
      
      response_data.stop.timezone_offset = offset;

      let response = dbproto.DeparturesBoardResponse.encode(response_data).finish();

      console.log("Processed departures board:");
      console.log(JSON.stringify(response_data));
      // console.log(dbproto.DeparturesBoardResponse.decode(response));

      let array = [];
      for(let i = 0; i < response.byteLength; i++) {
        array.push(response[i]);
      }

      console.log('Beginning transmission');

      transmitBuffer(array);
      } catch(e) {
        console.log("Error occurred");
        console.log(e.message);
        console.log("Stack trace:");
        console.log(e.stack);
      }
    });

    } catch(e) {
      console.log("Error occurred");
      console.log(e.message);
      console.log("Stack trace:");
      console.log(e.stack);
    }
  });
}

// MARK: - Transmission of data

function transmitBuffer(array) {
  var index = 0;
  var arrayLength = array.length;

  // Transmit the length for array allocation
  Pebble.sendAppMessage({
    'ChunkType': ChunkType.DeparturesBoardResponse,
    'DataLength': arrayLength
  }, function() {
    // Success, begin sending chunks
    sendChunk(array, index, arrayLength);
  }, function(e) {
    console.log('Failed to initiate buffer transfer!');
    console.log(e);
  })
}

function sendChunk(array, index, arrayLength) {
  try {
  // Determine the next chunk size
  var chunkSize = MAX_CHUNK_SIZE;
  if(arrayLength - index < MAX_CHUNK_SIZE) {
    // Resize to fit just the remaining data items
    chunkSize = arrayLength - index;
  }

  // Prepare the dictionary
  var dict = {
    'ChunkType': ChunkType.DeparturesBoardResponse,
    'DataChunk': array.slice(index, index + chunkSize),
    'ChunkSize': chunkSize,
    'Index': index
  };

  // console.log('Sending chunk ' + index);
  // console.log(JSON.stringify(dict));

  // Send the chunk
  Pebble.sendAppMessage(dict, function() {
    // console.log('Successfully sent chunk ' + index);

    // Success
    index += chunkSize;

    if(index < arrayLength) {
      // Send the next chunk
      sendChunk(array, index, arrayLength);
    } else {
      console.log('Completed transmission');
      // Complete!
      Pebble.sendAppMessage({
        'ChunkType': ChunkType.DeparturesBoardResponse,
        'Complete': 1,
      });
    }
  }, function(e) {
    console.log('Failed to send chunk with index ' + index);
    console.log(e);
  });
  } catch(e) {
    console.log("Error occurred");
    console.log(e.message);
    console.log("Stack trace:");
    console.log(e.stack);
  }
}

// MARK: - Event listeners
// Pebble.addEventListener('ready', () => getDeparturesBoard("CUS", "metra", 1785549849, 1785553456));

Pebble.addEventListener('ready', function() {
  console.log('PebbleKit JS ready.');

  // Update s_js_ready on watch
  Pebble.sendAppMessage({
    'ChunkType': ChunkType.JSReady,
    'DataLength': 0,
    'Complete': 1,
  });
});

// Get AppMessage events
Pebble.addEventListener('appmessage', function(e) {
  // Get the dictionary from the message
  const dict = e.payload;

  console.log('Got message: ' + JSON.stringify(dict));

  // We assume that it's just a single chunk of DeparturesBoardRequest
  if(dict['ChunkType'] === ChunkType.DeparturesBoardRequest) {
    if(dict['DataLength']&& dict['DataLength'] === dict['ChunkSize'] && dict['Index'] === 0) {
      // TODO -- Why do I have to use '10000' instead of 'DataChunk', but only in the emulator
      let decoded;
      if(dict['10000']) {
        decoded = dbproto.DeparturesBoardRequest.decode(dict['10000']);
      } else if(dict['DataChunk']) {
        decoded = dbproto.DeparturesBoardRequest.decode(dict['DataChunk']);
      }
      console.log('Decoded: ' + JSON.stringify(decoded));

      getDeparturesBoard(decoded.stop_id, decoded.chateau_id, decoded.greater_than_time, decoded.less_than_time);
    }
  }
});


// MARK: - (Old) Example departures board

// const response = dbproto.DeparturesBoardResponse.encode({
// 	success: true,

//   stop: {
//     stop_name: "Chicago Union Station",
//     timezone: "America/Chicago",
//     timezone_offset: -18000,
//   },

//   alerts: [
//     {
//       header_text: "MDW Inbound Delayed",
//       description_text: "MDW inbound and trains may be operating up to 45 minutes behind schedule due to earlier mechanical problems. Please visit MetraTracker.com for the location of your train."
//     }
// 	],

//   stop_events: [
//     {
//       scheduled_arrival: 1782583920,
//       scheduled_departure: 1782583920,

//       trip_modified: false,
//       stop_cancelled: false,
//       trip_cancelled: false,
//       trip_deleted: false,

//       headsign: "Chicago Union Station",
//       trip_short_name: "2714",

//       route_name: "MD-W",
//       route_color: GColorPastelYellowARGB8,
//       route_text_color: GColorBlackARGB8,
//       route_type: dbproto.RouteType.RAIL,

//       agency_name: "Metra",
//     },
//     {
//       scheduled_arrival: 1782584400,
//       scheduled_departure: 1782584400,

//       trip_modified: false,
//       stop_cancelled: false,
//       trip_cancelled: false,
//       trip_deleted: false,

//       headsign: "Chicago Union Station",
//       trip_short_name: "2016",

//       route_name: "BNSF",
//       route_color: GColorDarkGreenARGB8,
//       route_text_color: GColorWhiteARGB8,
//       route_type: dbproto.RouteType.RAIL,

//       agency_name: "Metra",
//     },
//     {
//       scheduled_arrival: 1782585180,
//       scheduled_departure: 1782585180,

//       trip_modified: false,
//       stop_cancelled: false,
//       trip_cancelled: false,
//       trip_deleted: false,
      
//       headsign: "Aurora",
//       trip_short_name: "2015",

//       route_name: "BNSF",
//       route_color: GColorDarkGreenARGB8,
//       route_text_color: GColorWhiteARGB8,
//       route_type: dbproto.RouteType.RAIL,

//       agency_name: "Metra",
//     },
// 	],
// }).finish();

// console.log('Success building sample response');

} catch(e) {
	console.log("Error occurred");
	console.log(e.message);
	console.log("Stack trace:");
	console.log(e.stack);
}

