// Polyfills for TextDecoder and TextEncoder
// required for pbjs-minimal.js

try {

require('fast-text-encoding');

var keys = require('message_keys');

console.log("catenary-proto PKJS process");

var dbproto = require('./proto/departures_board.pb.js');
console.log("Success importing proto");

const ChunkType = {
  DeparturesBoardRequest: 0,
  DeparturesBoardResponse: 1,
};

const BUFFER_SIZE = 8000;

// try {
// } catch (e) {
//   console.log("Error requiring proto: " + e.message);
//   console.log("Stack: " + e.stack);
// }

const GColorPastelYellowARGB8 = 0b11111110;
const GColorBlackARGB8 = 0b11000000;
const GColorDarkGreenARGB8 = 0b11000100;
const GColorWhiteARGB8 = 0b11111111;

// xhrRequest is from Pebble tutorial
function xhrRequest(url, type, callback, errorCallback = function(){
  console.log("Error fetching URL " + url);
}) {
	var xhr = new XMLHttpRequest();
	xhr.onload = function() {
    if(this.status >= 200 && this.status < 300) {
      callback(this.responseText);
    } else {
      errorCallback();
    }
	};
  xhr.onerror = errorCallback;
  xhr.onabort = errorCallback;
	xhr.open(type, url);
	xhr.send();
}

// getUtcOffsetSeconds is generated by Claude-Sonnet-4.6
function getUtcOffsetSeconds(ianaTimezone, unixTimestamp) {
  const date = new Date(unixTimestamp * 1000);

  // Parse the wall-clock time in both zones as if they were the same zone —
  // the device's local timezone cancels out, leaving just the difference.
  const utcWall = new Date(date.toLocaleString('en-US', { timeZone: 'UTC' }));
  const tzWall  = new Date(date.toLocaleString('en-US', { timeZone: ianaTimezone }));

  return Math.round((tzWall - utcWall) / 1000);
}

// hexToGColor8Argb is generated by Claude-Sonnet-4.6
function hexToGColor8Argb(hexStr, alpha = 255) {
  console.log("hexToGColor8Argb(" + hexStr + ", " + alpha + ")");
  // Strip leading '#' if present
  let hex = hexStr.replace(/^#/, '');

  // Support shorthand hex (#fff -> #ffffff)
  if (hex.length === 3) {
    hex = hex.split('').map(c => c + c).join('');
  }

  if (!/^[0-9a-fA-F]{6}$/.test(hex)) {
    throw new Error(`Invalid hex color string: "${hexStr}"`);
  }

  const red = parseInt(hex.substring(0, 2), 16);
  const green = parseInt(hex.substring(2, 4), 16);
  const blue = parseInt(hex.substring(4, 6), 16);

  // Mirror the C macro: each 8-bit channel keeps only its top 2 bits (>> 6)
  const r = (red >> 6) & 0x3;
  const g = (green >> 6) & 0x3;
  const b = (blue >> 6) & 0x3;
  const a = (alpha >> 6) & 0x3;

  // GColor8's bitfields (b, g, r, a, declared low-to-high) pack into a byte as:
  // argb = a<<6 | r<<4 | g<<2 | b
  const argb = (a << 6) | (r << 4) | (g << 2) | b;

  return argb; // 0-255, matches the .argb field of the union
}

function getDeparturesBoard() {
  const greater_than_time = 1782583302;
  var url = "https://birchdeparturesfromstop.catenarymaps.org/departures_at_stop?stop_id=CUS&chateau_id=metra&greater_than_time=1782583302&less_than_time=1782586913&include_shapes=false";

  xhrRequest(url, 'GET', function(response_text){
    try {
    var json = JSON.parse(response_text);

    // console.log("Departures board from Internet:");
    // console.log(response_text);

    var response_data = {
      success: true,
      stop: {
        // TODO - More intelligent translations handling
        stop_name: json.primary.stop_name_translations.EN,
        timezone: json.primary.timezone,
        timezone_offset: getUtcOffsetSeconds(json.primary.timezone),
      },
      alerts: [],
      stop_events: [],
    };

    for(chateau_alerts of Object.values(json.alerts)) {
      for(alert_data of Object.values(chateau_alerts)) {
        // console.log("Processing alert");
        // console.log(JSON.stringify(alert_data));
        response_data.alerts.push({
          header_text: alert_data.header_text.translation.find((translation) => translation.language.toLowerCase() == "en").text,
          description_text: alert_data.description_text.translation.find((translation) => translation.language.toLowerCase() == "en").text,
        });
      }
    }

    for(event_data of json.events) {
      // console.log("Processing stop event");
      // console.log(JSON.stringify(event_data));
      const route = json.routes[event_data.chateau][event_data.route_id];
      const agency = json.agencies[route.chateau][route.agency_id];

      response_data.stop_events.push({
        scheduled_arrival: event_data.scheduled_arrival,
        scheduled_departure: event_data.scheduled_departure,

        trip_modified: event_data.trip_modified,
        stop_cancelled: event_data.stop_cancelled,
        trip_cancelled: event_data.trip_cancelled,
        trip_deleted: event_data.trip_deleted,

        headsign: event_data.headsign,
        trip_short_name: event_data.trip_short_name,

        // TODO - Handle translations and absence of translations for route stuff
        route_name: route.long_name ? route.long_name : route.short_name,
        route_color: route.color ? hexToGColor8Argb(route.color) : GColorWhiteARGB8,
        route_text_color: route.text_color ? hexToGColor8Argb(route.text_color) : GColorBlackARGB8,
        route_type: route.route_type,

        // TODO - Handle translations and absence of translations for agency name
        agency_name: agency.agency_name,
      });
    }

    let response = dbproto.DeparturesBoardResponse.encode(response_data).finish();

    console.log("Processed departures board from Internet:");
    console.log(dbproto.DeparturesBoardResponse.decode(response));

    var array = [];
    for(var i = 0; i < response.byteLength; i++) {
      array.push(response[i]);
    }

    console.log('Beginning transmission');

    transmitBuffer(array);

    } catch(e) {
      console.log("Error occurred");
      console.log(e.message);
      console.log("Stack trace:");
      console.log(e.stack);
    }
  });
}

getDeparturesBoard();

// const response = dbproto.DeparturesBoardResponse.encode({
// 	success: true,

//   stop: {
//     stop_name: "Chicago Union Station",
//     timezone: "America/Chicago",
//     timezone_offset: -18000,
//   },

//   alerts: [
//     {
//       header_text: "MDW Inbound Delayed",
//       description_text: "MDW inbound and trains may be operating up to 45 minutes behind schedule due to earlier mechanical problems. Please visit MetraTracker.com for the location of your train."
//     }
// 	],

//   stop_events: [
//     {
//       scheduled_arrival: 1782583920,
//       scheduled_departure: 1782583920,

//       trip_modified: false,
//       stop_cancelled: false,
//       trip_cancelled: false,
//       trip_deleted: false,

//       headsign: "Chicago Union Station",
//       trip_short_name: "2714",

//       route_name: "MD-W",
//       route_color: GColorPastelYellowARGB8,
//       route_text_color: GColorBlackARGB8,
//       route_type: dbproto.RouteType.RAIL,

//       agency_name: "Metra",
//     },
//     {
//       scheduled_arrival: 1782584400,
//       scheduled_departure: 1782584400,

//       trip_modified: false,
//       stop_cancelled: false,
//       trip_cancelled: false,
//       trip_deleted: false,

//       headsign: "Chicago Union Station",
//       trip_short_name: "2016",

//       route_name: "BNSF",
//       route_color: GColorDarkGreenARGB8,
//       route_text_color: GColorWhiteARGB8,
//       route_type: dbproto.RouteType.RAIL,

//       agency_name: "Metra",
//     },
//     {
//       scheduled_arrival: 1782585180,
//       scheduled_departure: 1782585180,

//       trip_modified: false,
//       stop_cancelled: false,
//       trip_cancelled: false,
//       trip_deleted: false,
      
//       headsign: "Aurora",
//       trip_short_name: "2015",

//       route_name: "BNSF",
//       route_color: GColorDarkGreenARGB8,
//       route_text_color: GColorWhiteARGB8,
//       route_type: dbproto.RouteType.RAIL,

//       agency_name: "Metra",
//     },
// 	],
// }).finish();

// console.log('Success building sample response');

Pebble.addEventListener('ready', getDeparturesBoard);

function transmitBuffer(array) {
  var index = 0;
  var arrayLength = array.length;

  // Transmit the length for array allocation
  Pebble.sendAppMessage({
    'ChunkType': ChunkType.DeparturesBoardResponse,
    'DataLength': arrayLength
  }, function() {
    // Success, begin sending chunks
    sendChunk(array, index, arrayLength);
  }, function(e) {
    console.log('Failed to initiate buffer transfer!');
    console.log(e);
  })
}

function sendChunk(array, index, arrayLength) {
  try {
  // Determine the next chunk size
  var chunkSize = BUFFER_SIZE;
  if(arrayLength - index < BUFFER_SIZE) {
    // Resize to fit just the remaining data items
    chunkSize = arrayLength - index;
  }

  // Prepare the dictionary
  var dict = {
    'ChunkType': ChunkType.DeparturesBoardResponse,
    'DataChunk': array.slice(index, index + chunkSize),
    'ChunkSize': chunkSize,
    'Index': index
  };

  console.log('Sending chunk ' + index);
  console.log(JSON.stringify(dict));

  // Send the chunk
  Pebble.sendAppMessage(dict, function() {
    console.log('Successfully sent chunk ' + index);

    // Success
    index += chunkSize;

    if(index < arrayLength) {
      // Send the next chunk
      sendChunk(array, index, arrayLength);
    } else {
      console.log('Completed transmission');
      // Complete!
      Pebble.sendAppMessage({
        'ChunkType': ChunkType.DeparturesBoardResponse,
        'Complete': 0
      });
    }
  }, function(e) {
    console.log('Failed to send chunk with index ' + index);
    console.log(e);
  });
  } catch(e) {
    console.log("Error occurred");
    console.log(e.message);
    console.log("Stack trace:");
    console.log(e.stack);
  }
}

} catch(e) {
	console.log("Error occurred");
	console.log(e.message);
	console.log("Stack trace:");
	console.log(e.stack);
}

